version: '2'
services:
  streams:
    image: mapr/mapr-streams-websocket:0.1.0-SNAPSHOT
    ports:
      - 8081:8080
    environment:
      - MAPR_CLUSTER=cluster1
      - MAPR_CLDB_HOSTS=192.168.56.101
      - MAPR_CONTAINER_USER=mapr
    networks:
      - mapr-network
  ojai:
    image: mapr/mapr-db-ojai:0.1.0-SNAPSHOT
    ports:
      - 8082:8080
    environment:
      - MAPR_CLUSTER=cluster1
      - MAPR_CLDB_HOSTS=192.168.56.101
      - MAPR_CONTAINER_USER=mapr
      - MAPR_MOUNT_PATH=/mapr
      - cap-add=SYS_ADMIN
      - cap-add=SYS_RESOURCE
      - device=/dev/fuse
    networks:
      - mapr-network
networks:
  mapr-network:
    driver: bridge